### ISSUE TITLE
3.0 - 

### ISSUE THREAD

**Issue by zackkatz** [awesomemotive/easy-digital-downloads#9334]
### Expected behavior
When I run the CLI EDD migration command, it will not complete migrating payments. 

```
Fatal error: Uncaught Error: The script tried to modify a property on an incomplete object. Please ensure that the class definition "EDD_DB_Customers" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /sites/www.example.com/files/wp-includes/formatting.php:5010
Stack trace:
#0 /sites/www.example.com/files/wp-includes/formatting.php(5010): map_deep()
#1 /sites/www.example.com/files/wp-includes/formatting.php(5010): map_deep()
#2 /sites/www.example.com/files/wp-includes/formatting.php(5005): map_deep()
#3 /sites/www.example.com/files/wp-includes/formatting.php(5005): map_deep()
#4 /sites/www.example.com/files/wp-includes/formatting.php(5005): map_deep()
#5 /sites/www.example.com/files/wp-includes/formatting.php(2799): map_deep()
#6 /sites/www.example.com/files/wp-includes/formatting.php(5634): stripslashes_deep()
#7 /sites/www.example.com/files/wp-includes/meta.php(53): wp_unslash()
#8 /sites/www.example.com/files/wp-content/plugins/easy-digital-downloads/includes/orders/functions/meta.php(30): add_metadata()
#9 /sites/www.example.com/files/wp-content/plugins/easy-digital-downloads/includes/admin/upgrades/v3/class-data-migrator.php(1295): edd_add_order_meta()
#10 /sites/www.example.com/files/wp-content/plugins/easy-digital-downloads/includes/class-edd-cli.php(1339): EDD\Admin\Upgrades\v3\Data_Migrator::orders()
#11 /sites/www.example.com/files/wp-content/plugins/easy-digital-downloads/includes/class-edd-cli.php(833): EDD_CLI->migrate_payments()
#12 [internal function]: EDD_CLI->v30_migration()
```

### Information (if a specific version is affected):
PHP Version: 8.0

EDD Version (or branch): 3.0.2.1

WordPress Version: 6.0.1

Any other relevant information:

**Comment by cklosowski** [comment]
@zackkatz This looks like it failed while trying to do some payment meta. Do you know exactly where it failed or maybe you can send me a staging environment where we can look at this data to see what might be happening? You can always reach out at cklosowski@awesomemotive.com

**Comment by cartoonsmart** [comment]
I had some issues upgrading to EDD 3.0 because my database was MySQL5.5.  Created a new 5.7 db, moved everything over, and no problems since.  Zacks fatal error read like some of what I was running into.

**Comment by tomusborne** [comment]
@zackkatz @cklosowski Was this ever figured out? I'm running into the same issue on one of our sites. Doesn't happen on staging, but happened on the live site (had to restore a backup).

**Comment by ciorici** [comment]
I had a similar issue, and in my case, it was caused by some database tables related to **WordFence**.
