### ISSUE TITLE
Uncaught Error: Class "EDD\\Telemetry\\EDD\\Telemetry\\Data" not found 

### ISSUE THREAD

**Issue by nesges** [awesomemotive/easy-digital-downloads#9710]
## Bug Report
```
[Fri Feb 09 09:42:52.306412 2024] [proxy_fcgi:error] [pid 606243] [client 127.0.0.1:42818] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class "EDD\\Telemetry\\EDD\\Telemetry\\Data" not found in /var/www/html/d3/dnddeutsch.de/wordpress/wp-content/plugins/easy-digital-downloads/src/Telemetry/Tracking.php:72\nStack trace:\n#0 /var/www/html/d3/dnddeutsch.de/wordpress/wp-content/plugins/easy-digital-downloads/src/Telemetry/Tracking.php(93): EDD\\Telemetry\\Tracking->setup_data()\n#1 /var/www/html/d3/dnddeutsch.de/wordpress/wp-content/plugins/easy-digital-downloads/src/Telemetry/Tracking.php(126): EDD\\Telemetry\\Tracking->send_checkin()\n#2 /var/www/html/d3/dnddeutsch.de/wordpress/wp-includes/class-wp-hook.php(324): EDD\\Telemetry\\Tracking->check_for_settings_optin()\n#3 /var/www/html/d3/dnddeutsch.de/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters()\n#4 /var/www/html/d3/dnddeutsch.de/wordpress/wp-content/plugins/easy-digital-downloads/includes/admin/settings/register-settings.php(341): apply_filters()\n#5 /var/www/html/d3/dnddeutsch.de/wordpress/wp-includes/class-wp-hook.php(326): edd_setti...', referer: https://www.dnddeutsch.de/wp-admin/update-core.php
```

### Steps to reproduce the behavior
1) Update any other plugin
2) View webservers log

### Information (if a specific version is affected):
PHP Version: 8.1.2

EDD Version (or branch): 3.2.7.1 

WordPress Version: 6.4.3

**Comment by mihaijoldis** [comment]
This is now resolved as of EDD 3.2.8
