### ISSUE TITLE
PHP Fatal error because of `edds_get_elements_mode()` in `StripeEarlyFraudWarning.php`

### ISSUE THREAD

**Issue by goncalovf** [awesomemotive/easy-digital-downloads#9755]
### Expected behavior
When I go to the `/wp-admin/edit.php?post_type=download&page=edd-emails` page, I have a full list of emails to manage.

### Actual behavior
When I go to the `/wp-admin/edit.php?post_type=download&page=edd-emails` page, I get the PHP Fatal error:

```
[23-Aug-2024 14:26:07 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function EDD\Emails\Templates\edds_get_elements_mode() in /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Emails/Templates/StripeEarlyFraudWarning.php:136
Stack trace:
#0 /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Emails/Templates/EmailTemplate.php(299): EDD\Emails\Templates\StripeEarlyFraudWarning->are_base_requirements_met()
#1 /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Emails/Templates/EmailTemplate.php(152): EDD\Emails\Templates\EmailTemplate->is_enabled()
#2 /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Admin/Emails/ListTable.php(231): EDD\Emails\Templates\EmailTemplate->__get('status')
#3 /var/www/html/wp-admin/includes/class-wp-list-table.php(1724): EDD\Admin\Emails\ListTable->single_row(Object(EDD\Emails\Templates\StripeEarlyFraudWarning))
#4 /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Admin/Emails/ListTable.php(201): WP_List_Table->display_rows()
#5 /var/www/html/wp-admin/includes/class-wp-list-table.php(1636): EDD\Admin\Emails\ListTable->display_rows_or_placeholder()
#6 /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Admin/Emails/Screen.php(128): WP_List_Table->display()
#7 /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Admin/Emails/Screen.php(58): EDD\Admin\Emails\Screen::render_table()
#8 /var/www/html/wp-includes/class-wp-hook.php(324): EDD\Admin\Emails\Screen::render('')
#9 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#10 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 /var/www/html/wp-admin/admin.php(259): do_action('download_page_e...')
#12 /var/www/html/wp-admin/edit.php(10): require_once('/var/www/html/w...')
#13 {main}
  thrown in /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Emails/Templates/StripeEarlyFraudWarning.php on line 136
```
At first, I thought that this was caused by `edds_get_elements_mode()` being called from the `EDD\Emails\Templates` namespace ([here](https://github.com/awesomemotive/easy-digital-downloads/blob/main/src/Emails/Templates/StripeEarlyFraudWarning.php#L136)), when it is placed in a file without a namespace ([here](https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/gateways/stripe/includes/elements/functions.php#L27)). But even when I replace...

```php
	public function are_base_requirements_met(): bool {
		return edd_is_gateway_active( 'stripe' ) && 'payment-elements' === edds_get_elements_mode();
	}
```

... with ...

```php
	public function are_base_requirements_met(): bool {
		return edd_is_gateway_active( 'stripe' ) && 'payment-elements' === \edds_get_elements_mode();
	}
```

I still get the same error:

```php
[23-Aug-2024 14:46:03 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function edds_get_elements_mode() in /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Emails/Templates/StripeEarlyFraudWarning.php:136
Stack trace:
#0 /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Emails/Templates/EmailTemplate.php(299): EDD\Emails\Templates\StripeEarlyFraudWarning->are_base_requirements_met()
#1 /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Emails/Templates/EmailTemplate.php(152): EDD\Emails\Templates\EmailTemplate->is_enabled()
#2 /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Admin/Emails/ListTable.php(231): EDD\Emails\Templates\EmailTemplate->__get('status')
#3 /var/www/html/wp-admin/includes/class-wp-list-table.php(1724): EDD\Admin\Emails\ListTable->single_row(Object(EDD\Emails\Templates\StripeEarlyFraudWarning))
#4 /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Admin/Emails/ListTable.php(201): WP_List_Table->display_rows()
#5 /var/www/html/wp-admin/includes/class-wp-list-table.php(1636): EDD\Admin\Emails\ListTable->display_rows_or_placeholder()
#6 /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Admin/Emails/Screen.php(128): WP_List_Table->display()
#7 /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Admin/Emails/Screen.php(58): EDD\Admin\Emails\Screen::render_table()
#8 /var/www/html/wp-includes/class-wp-hook.php(324): EDD\Admin\Emails\Screen::render('')
#9 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#10 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 /var/www/html/wp-admin/admin.php(259): do_action('download_page_e...')
#12 /var/www/html/wp-admin/edit.php(10): require_once('/var/www/html/w...')
#13 {main}
  thrown in /var/www/html/wp-content/plugins/easy-digital-downloads-pro/src/Emails/Templates/StripeEarlyFraudWarning.php on line 136
```

My (temporary) solution was just to remove ` && 'payment-elements' === \edds_get_elements_mode()` entirely, having just the following:

```php
	public function are_base_requirements_met(): bool {
		return edd_is_gateway_active( 'stripe' );
	}
```

### Information (if a specific version is affected):
PHP Version: 8.2

EDD Version (or branch): 3.3.3

WordPress Version: 6.4.2

**Comment by robincornett** [comment]
@goncalovf can you give me some more information about your site setup? Specifically, I'm wondering if you are using Stripe Pro, and if so, what version. You may want to [reach out directly to our support team](https://easydigitaldownloads.com/support/) for help with this so that you can generate a system info file to help them debug.

**Comment by goncalovf** [comment]
I'm sorry, I just realized that this was my fault. I hadn't updated the `Easy Digital Downloads - Stripe Pro Payment Gateway` plugin, which was still in version 2.8.13.1. I'm sorry for the trouble I caused.

I also submitted a support ticket but I don't see how I can access it to close it. I'll wait for a response and inform that it's fixed then.
